name: Release

on:
  push:
    tags:
      - "v*"
      - "v*.*"
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build with make
        run: make

      - name: Upload Release Asset
        uses: softprops/action-gh-release@v2
        with:
          files: dist/sms
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

